{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div id="maincontent"><div id="fix">

<div id="maincontent-design">

{def $base_uri=concat( 'ezapprove2/select_approver/', $approval_status.id, '/', $approval_status.step )}

<form name="SelectApprover" method="post" action={$base_uri|ezurl}>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{'Select users for content approval <%object_name>'|i18n( 'ezapprove2',, hash( '%object_name', $object.name ) )|wash}</h2>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

{if $warning}
    <div class="message-warning">
        <h2>{$warning|wash}</h2>
    </div>
{/if}

{if $approval_status.approve2_event.require_all_approve|eq(2)}
    <div class="block">
        <div class="element">
            {'Select minimum number of required approvals.'|i18n( 'ezapprove2' )}
            <select name="RequiredNumberApproves_{$event.id}">
            <option value="-1" {cond( $approval_status.required_num_approvers|eq(-1), 'selected="selected"', '')}>{'Any'|i18n( 'design/admin/workflow/eventtype/edit' )}</option>
            {for 1 to max( 1, count( $approval_status.approve_user_list ) ) as $num}
            <option value="{$num}" {cond( $approval_status.required_num_approvers|eq($num), 'selected="selected"', '')}>{$num}</option>
            {/for}
        </select>

        </div>
    </div>

{/if}

<div class="block">
{if $approval_status.approve_user_list}
    <table class="list" cellspacing="0">
    <tr>
        <th class="tight">&nbsp;</th>
        <th>{'Approve users'|i18n( 'design/admin/workflow/eventtype/edit' )}</th>
    </tr>
    {foreach $approval_status.approve_user_list as $approveUserLink
             sequence array( bglight, bgdark ) as $sequence}
        <tr class="{$sequence}">
            <td><input type="checkbox" name="DeleteApproveUserIDArray[]" value="{$approveUserLink.id}" />
            <input type="hidden" name="ApproveUserID[]" value="{$approveUserLink.id}" /></td>
            <td>{$approveUserLink.user.contentobject.name|wash}</td>
        </tr>
    {/foreach}
    </table>
{else}
    <p>{'No users selected.'|i18n( 'design/admin/workflow/eventtype/edit' )}</p>
{/if}

<input class="button" type="submit" name="RemoveApproveUsers" value="{'Remove selected'|i18n( 'design/admin/workflow/eventtype/edit' )}" />
<input class="button" type="submit" name="AddApproveUsers" value="{'Add users'|i18n( 'design/admin/workflow/eventtype/edit' )}" />

</div>

</div>

{* DESIGN: Content END *}</div></div></div>


    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">

    <div align="right"><input class="button" type="submit" name="SubmitButton" value="{'Continue'|i18n( 'design/admin/workflow/eventtype/edit' )}" /></div>

{* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>


</form>



</div></div></div>